apiVersion: v1
kind: Pod
metadata:
  name: no-hostpath-pod
  namespace: audit-zone
  labels:
    app: insecure
    violation: hostpath
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sleep", "3600"]
    volumeMounts:
    - name: storage
      mountPath: /data
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ "ALL" ]
      seccompProfile:
        type: RuntimeDefault
  volumes:
  - name: storage
    emptyDir: {}
  restartPolicy: Never