apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-back-end-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-back-end-api
  template:
    metadata:
      labels:
        app: admin-back-end-api
        role: admin-back-end-api
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.0-alpine
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: admin-back-end-api-svc
spec:
  selector:
    app: admin-back-end-api
  ports:
    - port: 80