apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: audit-zone
  labels:
    app: insecure
    violation: hostpath
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sleep", "3600"]
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /
      type: Directory
  restartPolicy: Never