apiVersion: v1
kind: Pod
metadata:
  name: root-user-pod
  namespace: audit-zone
  labels:
    app: insecure
    violation: root-user
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command: ["sleep", "3600"]
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
  restartPolicy: Never